[package]
name = "littensy/vide-charm"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["package.json"]

[dependencies]
charm = "littensy/charm@^0.9"
Vide = "centau/vide@^0.3"
