[package]
name = "littensy/vide-charm"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
charm = "littensy/charm@^0.10"
Vide = "centau/vide@^0.3"
